# Site settings
title: Code Hideout
lang: pl
email: Sajgoniarz1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: Sajgoniarz
name: Marek Naharnowicz
github_username: Sajgoniarz
github_avatar_link : https://avatars2.githubusercontent.com/u/2995236
pagelist:
 - title: Blog
   icon: home
   link: /
paginate: 6
paginate_path: /:num/
# Build settings
markdown: kramdown
