title: Code Hideout
lang: pl
email: Sajgoniarz1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: Sajgoniarz
author: Marek Naharnowicz
github_username: Sajgoniarz
github_avatar_link : https://avatars2.githubusercontent.com/u/2995236
background: BG.png
pagelist:
 - title: Blog
   icon: home
   link: /
 - title: Kursy
   icon: book
   link: /courses
 - title: O mnie
   icon: account_circle
   link: /about
# Courses list & config
courses:
 - title: Jekyll
   category: jekyll
   img: 3083652.png
   list-bg-color: grey-800
   list-icon-bg-color: yellow-700
   list-font-color: grey-50
 - title: HTML5
   category: html
   img: html5logo.svg
   list-bg-color: orange-800
   list-icon-bg-color: yellow-400
   list-font-color: grey-50
# Blog post config
post-default-header-bg-color: blue-grey-800
post-default-header-text-color: teal-300
paginate: 6
paginate_path: /:num/
# Build settings
markdown: kramdown
